### ISSUE TITLE
Add Go 1.20

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator-images#10]
Go 1.20 was released on 1st of February 2023 - https://go.dev/blog/go1.20. We should add a corresponding image.

**Comment by tnozicka** [comment]
waiting for .1 but feel free to send a bump when it's there ;)

**Comment by tnozicka** [comment]
actually there is 1.20.2 already so you are good to go

**Comment by rzetelskik** [comment]
Closing as completed in https://github.com/scylladb/scylla-operator-images/pull/12
