### ISSUE TITLE
Golang builders are missing tools

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator-images#57]
```
 /bin/bash: line 1: find: command not found 
```
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2116/pull-scylla-operator-master-verify/1833120810970124288#1:build-log.txt%3A11

**Comment by rzetelskik** [comment]
```
daemon_test.go:27: can't create dbus connection to user's systemd: exec: "dbus-launch": executable file not found in $PATH
```

https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/2115/pull-scylla-operator-master-unit/1833114321538781184#1:build-log.txt%3A116
