### ISSUE TITLE
Use ubuntu 22.0.4 base image

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-operator-images#6]
Align with the AMI, latest software, less vulnerabilities, etc.

**Comment by mykaul** [comment]
@tnozicka - can we get it done for MS4?

**Comment by tnozicka** [comment]
we should be able to do that for MS 4

longterm, can we migrate to something having a smaller surface area like ubi-minimal?

**Comment by mykaul** [comment]
> we should be able to do that for MS 4
> 
> longterm, can we migrate to something having a smaller surface area like ubi-minimal?

1. I had hard time moving my team @ Red Hat to use ubi-micro - I succeed (partially) with ubi-minimal, though I do believe micro is much more effective.
2. I did not see ubuntu-minimal for *containers* (it exists for the AMI images and we have made the changes to use it in 5.2). It's unclear to me if there is value in moving in the open source to ubi (RH based). The FAQ (https://developers.redhat.com/articles/ubi-faq#ubi_details) seem to be OK with using it:
```
15. Do I need a subscription to use UBI?
No. The Red Hat Universal Base Images and all associated content can be used for development and deployment without the need for a Red Hat subscription. However, for a fully supported operational experience and access to an expanded list of non-UBI tools, containers built on UBI must be deployed on a Red Hat platform such as OpenShift or Red Hat Enterprise Linux.

Accessing non-UBI content does require a Red Hat subscription.

```

But also:
```
Redistribution
20. Can I freely distribute applications built on UBI?
Yes, applications built on the Red Hat Universal Base Images and UBI-compatible tools and packages can be distributed with the embedded UBI content in the base image, as per the UBI EULA. Software vendors and community projects which build on UBI may have additional EULAs, which apply to their layered software.

21. Can I distribute my UBI-based container images without using Red Hat’s registry?
Yes. Users can choose their own registry.

22. Can I add non-UBI RPMs to a UBI image and still redistribute the resultant container image on a non-Red Hat platform?
No, only Red Hat packages assigned to the UBI EULA can be redistributed. The EULA, under which UBI is governed, allows users to distribute a set of container images and RPMs delivered as part of UBI. Container images and RPMs which are covered by a different EULA have different rights and restrictions. Of course, and in general, you can expect any community open source technology to be redistributable.
```

cc @avikivity for his thoughts on this.

**Comment by tnozicka** [comment]
micro doesn't have a package manager and we need at least microdnf since the image is share by some of our infra binaries that need some OS packages

I don't see the licensing as an issue, effectivelly you just can't used you machines RHEL to add extra packages, personally I think the centos repo with it would be fine but we really need just the basics like shell or mdadm

**Comment by mykaul** [comment]
> micro doesn't have a package manager and we need at least microdnf since the image is share by some of our infra binaries that need some OS packages

buildah mount ... and you are good.

> 
> I don't see the licensing as an issue, effectivelly you just can't used you machines RHEL to add extra packages, personally I think the centos repo with it would be fine but we really need just the basics like shell or mdadm

They warn against using CentOS packages (see above - 'Frankenstein' note). Especially with Stream that might be somewhat of a challenge (unless we maintain our own repo of the packages we need and update carefully in a controlled manner)

**Comment by tnozicka** [comment]
I know you can technically install packages into the new container, e.g. with --installroot but it requires another level of nesting by wrapping the install in yet another image, so I'd probably start small based on the existing infra.

Regarding centos I think their main reason is that if you install packages from other systems they can't support them which is obvious and fine with me. You'd get the same by using centos directly, expect the don't have minimal images with microdnf.
